[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -m "not integration"
markers =
    integration: marks tests that require real DB connection
