"""
db_invoices.py — Invoices table queries

Invoices are AI-generated bills linked to completed jobs.
Generated by invoice_agent after the owner texts in job completion.

Usage:
    from execution.db_invoices import save_invoice, update_invoice_status
"""

import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from execution.db_connection import get_client


def timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def save_invoice(
    job_id: str,
    client_id: str,
    customer_id: str,
    invoice_text: str,
    amount_due: float,
    due_date: str = None,
) -> str | None:
    """
    Save a generated invoice record.
    Called by invoice_agent after Claude generates the invoice text.

    Args:
        job_id:       UUID of the completed job
        client_id:    UUID of the client (business owner)
        customer_id:  UUID of the end customer
        invoice_text: Full invoice text generated by Claude
        amount_due:   Total dollar amount owed
        due_date:     ISO date string for payment due date (optional)

    Returns:
        New invoice UUID as a string, or None on failure.
    """
    try:
        supabase = get_client()
        record = {
            "job_id":       job_id,
            "client_id":    client_id,
            "customer_id":  customer_id,
            "invoice_text": invoice_text,
            "amount_due":   amount_due,
            "status":       "draft",
        }
        if due_date:
            record["due_date"] = due_date

        result = supabase.table("invoices").insert(record).execute()
        invoice_id = result.data[0]["id"]
        print(f"[{timestamp()}] INFO db_invoices: Saved invoice id={invoice_id} amount=${amount_due}")
        return invoice_id

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_invoices: save_invoice failed — {e}")
        return None


def update_invoice_status(invoice_id: str, status: str) -> bool:
    """
    Update invoice status. Stamps sent_at or paid_at timestamps automatically.
    Valid statuses: draft, sent, paid, overdue.

    Args:
        invoice_id: UUID of the invoice
        status:     New status string

    Returns:
        True on success, False on failure.
    """
    try:
        supabase = get_client()
        update = {"status": status}

        now = datetime.now(timezone.utc).isoformat()
        if status == "sent":
            update["sent_at"] = now
        elif status == "paid":
            update["paid_at"] = now

        supabase.table("invoices").update(update).eq("id", invoice_id).execute()
        print(f"[{timestamp()}] INFO db_invoices: Invoice {invoice_id} → status={status}")
        return True

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_invoices: update_invoice_status failed — {e}")
        return False


def get_overdue_invoices(client_id: str) -> list:
    """
    Return all sent invoices past their due date that haven't been paid.
    Used by the followup_agent for payment chasing.

    Args:
        client_id: UUID of the client

    Returns:
        List of invoice dicts, or empty list on error.
    """
    try:
        supabase = get_client()
        today = datetime.now().date().isoformat()

        result = (
            supabase.table("invoices")
            .select("*")
            .eq("client_id", client_id)
            .eq("status", "sent")
            .lt("due_date", today)
            .order("due_date")
            .execute()
        )
        print(f"[{timestamp()}] INFO db_invoices: get_overdue_invoices → {len(result.data)} overdue")
        return result.data or []

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_invoices: get_overdue_invoices failed — {e}")
        return []
