"""
db_proposals.py — Proposals table queries

Proposals are AI-generated estimates linked to jobs. The proposal_agent
creates them, the follow_up_agent chases them when they go cold.

Usage:
    from execution.db_proposals import save_proposal, get_pending_proposals
"""

import os
import sys
from datetime import datetime, timezone, timedelta

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from execution.db_connection import get_client


def timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def save_proposal(
    job_id: str,
    client_id: str,
    customer_id: str,
    proposal_text: str,
    amount: float,
) -> str | None:
    """
    Save a generated proposal and mark the linked job as 'estimated'.

    Args:
        job_id:        UUID of the job this proposal is for
        client_id:     UUID of the client (business owner)
        customer_id:   UUID of the end customer
        proposal_text: Full proposal text generated by the AI
        amount:        Estimated dollar amount

    Returns:
        New proposal UUID as a string, or None on failure.
    """
    try:
        supabase = get_client()
        record = {
            "job_id":          job_id,
            "client_id":       client_id,
            "customer_id":     customer_id,
            "proposal_text":   proposal_text,
            "amount_estimate": amount,
            "status":          "draft",
        }
        result = supabase.table("proposals").insert(record).execute()
        proposal_id = result.data[0]["id"]
        print(f"[{timestamp()}] INFO db_proposals: Saved proposal id={proposal_id} amount=${amount}")
        return proposal_id

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_proposals: save_proposal failed — {e}")
        return None


def update_proposal_status(proposal_id: str, status: str) -> bool:
    """
    Update proposal status. Also stamps sent_at or accepted_at timestamps.
    Valid statuses: draft, sent, accepted, rejected, expired.

    Args:
        proposal_id: UUID of the proposal
        status:      New status string

    Returns:
        True on success, False on failure.
    """
    try:
        supabase = get_client()
        update = {"status": status}

        # Stamp the appropriate timestamp based on the new status
        now = datetime.now(timezone.utc).isoformat()
        if status == "sent":
            update["sent_at"] = now
        elif status == "accepted":
            update["accepted_at"] = now

        supabase.table("proposals").update(update).eq("id", proposal_id).execute()
        print(f"[{timestamp()}] INFO db_proposals: Proposal {proposal_id} → status={status}")
        return True

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_proposals: update_proposal_status failed — {e}")
        return False


def get_pending_proposals(client_id: str) -> list:
    """
    Return all sent proposals with no response that are older than 3 days.
    These are the proposals the follow_up_agent should chase.

    Args:
        client_id: UUID of the client

    Returns:
        List of proposal dicts, or empty list on error.
    """
    try:
        supabase = get_client()

        # Cut-off: proposals sent more than 3 days ago with no response
        cutoff = (datetime.now(timezone.utc) - timedelta(days=3)).isoformat()

        result = (
            supabase.table("proposals")
            .select("*")
            .eq("client_id", client_id)
            .eq("status", "sent")
            .lt("sent_at", cutoff)
            .execute()
        )
        print(f"[{timestamp()}] INFO db_proposals: get_pending_proposals → {len(result.data)} proposals to chase")
        return result.data or []

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_proposals: get_pending_proposals failed — {e}")
        return []


def update_proposal_response(
    proposal_id: str,
    response_type: str,
    lost_reason: str = None,
    lost_reason_detail: str = None,
) -> bool:
    """
    Record how a customer responded to a proposal.
    Called by followup_agent after detecting acceptance or rejection.

    Args:
        proposal_id:        UUID of the proposal
        response_type:      "accepted", "declined", or "cold"
        lost_reason:        Reason code if declined (optional)
        lost_reason_detail: Owner's own words about why (optional)

    Returns:
        True on success, False on failure.
    """
    try:
        supabase = get_client()
        update = {
            "response_type": response_type,
            "responded_at":  datetime.now(timezone.utc).isoformat(),
        }
        if lost_reason:
            update["lost_reason"] = lost_reason
        if lost_reason_detail:
            update["lost_reason_detail"] = lost_reason_detail

        supabase.table("proposals").update(update).eq("id", proposal_id).execute()
        print(f"[{timestamp()}] INFO db_proposals: Proposal {proposal_id} response_type={response_type}")
        return True

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_proposals: update_proposal_response failed — {e}")
        return False


def get_latest_sent_proposal_for_customer(client_id: str, customer_id: str) -> dict | None:
    """
    Find the most recent sent proposal for a specific client/customer pair.
    Used by followup_agent when a customer texts in a response.

    Belt-and-suspenders: requires sent_at IS NOT NULL so any row that
    accidentally got status='sent' without a real send timestamp can't
    surface here. The legit /doc/send path always writes both fields
    together, so this filter is invisible to correct callers but blocks
    the failure mode that caused customers to receive draft estimates.

    Returns:
        Proposal dict, or None if not found / on error.
    """
    try:
        supabase = get_client()
        result = (
            supabase.table("proposals")
            .select("*")
            .eq("client_id", client_id)
            .eq("customer_id", customer_id)
            .eq("status", "sent")
            .not_.is_("sent_at", "null")
            .order("created_at", desc=True)
            .limit(1)
            .execute()
        )
        if result.data:
            print(f"[{timestamp()}] INFO db_proposals: Found latest sent proposal for customer")
        return result.data[0] if result.data else None

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_proposals: get_latest_sent_proposal_for_customer failed — {e}")
        return None


def get_cold_proposals(client_id: str, days: int = 14) -> list:
    """
    Return sent proposals with no response older than `days` days.
    These get marked cold and trigger the final message + why question.

    Args:
        client_id: UUID of the client
        days:      Age threshold in days (default 14)

    Returns:
        List of proposal dicts, or empty list on error.
    """
    try:
        supabase = get_client()
        cutoff = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()

        result = (
            supabase.table("proposals")
            .select("*")
            .eq("client_id", client_id)
            .eq("status", "sent")
            .is_("response_type", "null")
            .lt("sent_at", cutoff)
            .execute()
        )
        print(f"[{timestamp()}] INFO db_proposals: get_cold_proposals → {len(result.data)} cold ({days}+ days)")
        return result.data or []

    except Exception as e:
        print(f"[{timestamp()}] ERROR db_proposals: get_cold_proposals failed — {e}")
        return []
