"""
proposal_html.py — Converts proposal text into a styled HTML page
"""
from datetime import datetime


def build_proposal_html(
    proposal_text: str,
    customer_name: str,
    job_type: str,
    business_name: str,
    owner_name: str,
) -> str:
    lines = proposal_text.strip().split("\n")
    paragraphs = "".join(
        f"<p>{line}</p>" if line.strip() else "<br>"
        for line in lines
    )
    date_str = datetime.now().strftime("%B %d, %Y")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Proposal — {customer_name}</title>
  <style>
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: Georgia, serif;
      background: #f5f5f0;
      color: #1a1a1a;
      padding: 2rem 1rem;
    }}
    .card {{
      max-width: 640px;
      margin: 0 auto;
      background: #fff;
      border-radius: 8px;
      box-shadow: 0 2px 12px rgba(0,0,0,0.1);
      overflow: hidden;
    }}
    .header {{
      background: #1a3a2a;
      color: #fff;
      padding: 2rem;
    }}
    .header h1 {{
      font-size: 1.4rem;
      font-weight: normal;
      letter-spacing: 0.02em;
    }}
    .header .meta {{
      margin-top: 0.5rem;
      font-size: 0.85rem;
      opacity: 0.75;
    }}
    .body {{
      padding: 2rem;
      line-height: 1.75;
      font-size: 1rem;
    }}
    .body p {{ margin-bottom: 0.9rem; }}
    .footer {{
      background: #f0ede8;
      padding: 1rem 2rem;
      font-size: 0.8rem;
      color: #666;
      border-top: 1px solid #e0ddd8;
    }}
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <h1>{business_name}</h1>
      <div class="meta">Proposal for {customer_name} &nbsp;·&nbsp; {date_str}</div>
    </div>
    <div class="body">
      {paragraphs}
    </div>
    <div class="footer">
      Generated by {business_name} &nbsp;·&nbsp; {owner_name}
    </div>
  </div>
</body>
</html>"""
